name: .NET build and test

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/dotnet-build-and-test.yaml"
      - "Clarp/**"
      - "Clarp.Tests/**"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/dotnet-build-and-test.yaml"
      - "Clarp/**"
      - "Clarp.Tests/**"

jobs:
  build-and-test:
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/dotnet-build-and-test-with-osx.yaml@main